apiVersion: v1
kind: Service
metadata:
  name: {{ include "testserver.fullname" . }}-ssl 
  labels:
{{ include "testserver.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: http
      nodePort: {{ .Values.service.sslNodePort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "testserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
